### ISSUE TITLE
Use the transaction manager defined by the request.

### ISSUE THREAD

**Issue by mmerickel** [Pylons/pyramid_zodbconn#6]
https://github.com/Pylons/pyramid_zodbconn/blob/2bce04378e5d98e68cb49b3e4be47fe9e15a6ce1/pyramid_zodbconn/__init__.py#L49

This should be `primary_db.open(request.tm)` to  support the request's transaction manager from pyramid_tm. Currently the pyramid scaffold is broken without this and it'd be better to improve this than to revert the scaffold - however I cannot cut releases of this package.

**Comment by tseaver** [comment]
Are there any backward-compatibility issues with using `request.tm` (e.g., would we need to pin a minimum version of pyramid / pyramid_tm)?

Also, https://pypi.python.org/pypi/pyramid_zodbconn/ shows `mmericket` as an owner.

**Comment by mmerickel** [comment]
`request.tm` has been available on pyramid_tm since around 0.12 (sometime in 2015). If you want to support older versions the fix is pretty simply to just `getattr(request, 'tm', transaction.manager)`.

As far as pypi that must be just a precaution but I don't have any intention of working on this package - I've never done anything with ZODB and wouldn't trust myself to make any changes... I already broke the scaffold obviously :(
